import type { ClassCatalog, GradeLevel } from "./types";

export const CLASSES_BY_GRADE: Record<GradeLevel, ClassCatalog> = {
	9: {
		Core: [
			"English 9",
			"Honors English 9",
			"Algebra I",
			"Geometry",
			"Biology",
			"Earth Science",
			"World History",
			"Geography",
			"Physical Education",
			"Health",
		],
		"World languages": [
			"Spanish I",
			"Spanish II",
			"French I",
			"French II",
			"German I",
			"Chinese I",
			"Latin I",
		],
		Arts: ["Art I", "Drawing", "Painting", "Ceramics", "Graphic Design", "Photography"],
		"Music & performance": ["Band", "Orchestra", "Choir", "Theater"],
		"Speech & writing": ["Debate", "Journalism", "Creative Writing"],
		"STEM electives": [
			"Computer Science Explorations",
			"Intro to Programming",
			"Robotics",
			"Engineering Design",
		],
		Business: ["Business / Entrepreneurship", "Personal Finance"],
	},
	10: {
		Core: [
			"English 10",
			"Honors English 10",
			"Geometry",
			"Algebra II",
			"Chemistry",
			"Biology",
			"U.S. History",
			"World History",
			"Physical Education",
			"Health",
		],
		"World languages": [
			"Spanish II",
			"Spanish III",
			"French II",
			"French III",
			"German II",
			"Chinese II",
			"Latin II",
		],
		Arts: ["Art II", "Graphic Design", "Photography"],
		"Music & performance": ["Band", "Orchestra", "Choir", "Theater"],
		"Speech & writing": ["Debate", "Journalism", "Yearbook", "Speech"],
		"STEM electives": [
			"Computer Science Principles",
			"Intro to Web Development",
			"Robotics",
			"Engineering Design",
		],
		Business: ["Marketing", "Accounting"],
		AP: ["AP World History", "AP Computer Science Principles"],
	},
	11: {
		Core: [
			"English 11",
			"Honors English 11",
			"Algebra II",
			"Precalculus",
			"Statistics",
			"Physics",
			"Chemistry",
			"U.S. Government",
			"Economics",
		],
		"World languages": [
			"Spanish III",
			"Spanish IV",
			"French III",
			"French IV",
			"German III",
			"Chinese III",
			"Latin III",
		],
		"STEM electives": [
			"Computer Science A",
			"Data Science",
			"Cybersecurity",
			"Engineering",
			"Anatomy & Physiology",
			"Environmental Science",
			"Forensics",
		],
		Humanities: ["Psychology", "Sociology", "Philosophy"],
		Arts: ["Art III", "AP Studio Art"],
		"Music & performance": ["Band", "Orchestra", "Choir", "Theater"],
		"Speech & writing": ["Debate", "Journalism"],
		AP: [
			"AP U.S. History",
			"AP Language & Composition",
			"AP Calculus AB",
			"AP Statistics",
			"AP Biology",
			"AP Chemistry",
			"AP Physics 1",
			"AP Computer Science A",
			"AP Psychology",
			"AP Environmental Science",
		],
	},
	12: {
		Core: [
			"English 12",
			"Honors English 12",
			"AP Literature & Composition",
			"Precalculus",
			"Calculus",
			"Statistics",
			"Physics",
			"Government",
			"Economics",
		],
		"World languages": [
			"Spanish IV",
			"Spanish V",
			"AP Spanish Language",
			"French IV",
			"AP French Language",
			"German IV",
			"Chinese IV",
			"Latin IV",
		],
		"STEM electives": [
			"Computer Science A",
			"AP Computer Science A",
			"Data Science",
			"Web Development",
			"Mobile App Development",
			"Robotics",
			"Engineering Capstone",
			"Anatomy & Physiology",
			"Environmental Science",
		],
		Humanities: ["Psychology", "Sociology"],
		Business: ["Business Law", "Entrepreneurship", "Personal Finance"],
		Arts: ["Art IV", "AP Studio Art", "Yearbook", "Independent Study"],
		"Music & performance": ["Band", "Orchestra", "Choir", "Theater"],
		AP: [
			"AP Calculus AB",
			"AP Calculus BC",
			"AP Statistics",
			"AP U.S. Government",
			"AP Macroeconomics",
			"AP Microeconomics",
			"AP Biology",
			"AP Chemistry",
			"AP Physics 1",
			"AP Physics C",
			"AP Environmental Science",
			"AP Psychology",
		],
	},
};

export const COMMON_MAJORS = [
	"Computer Science",
	"Data Science",
	"Software Engineering",
	"Electrical Engineering",
	"Mechanical Engineering",
	"Civil Engineering",
	"Chemical Engineering",
	"Biomedical Engineering",
	"Industrial Engineering",
	"Mathematics",
	"Statistics",
	"Physics",
	"Chemistry",
	"Biology",
	"Neuroscience",
	"Psychology",
	"Economics",
	"Finance",
	"Accounting",
	"Business Administration",
	"Marketing",
	"Political Science",
	"International Relations",
	"History",
	"English",
	"Communications",
	"Journalism",
	"Philosophy",
	"Sociology",
	"Public Health",
	"Nursing",
	"Pre-Med",
	"Education",
	"Architecture",
	"Graphic Design",
	"Art",
	"Music",
	"Theater",
] as const;

export const COLLEGE_SUBJECTS = [
	"CS",
	"MA",
	"STAT",
	"PHYS",
	"CHEM",
	"BIOL",
	"ECON",
	"ENGL",
	"HIST",
	"POL",
	"PSY",
	"SOC",
	"COMM",
	"MGMT",
	"FIN",
	"MKTG",
	"ECE",
	"ME",
	"CE",
] as const;